/*
 * Created by Glic-Tech Ltd on 13-04-2021.
 *
 * Description: Controller class for opportunities.
 *
 * Last modified by Miko in Glic-Tech on 13-04-2021.
*/
public with sharing class Opportunity_con {
   /*
   * Description: Inserts records.
   *
   * Last modified by Miko in Glic-Tech on 13-04-2021.
   */
   @testvisible
   static void CreateClause(list<sObject> records){
      //try{ insert records; } catch(exception e){ insert new GlicW__Error_Log__c(GlicW__Error_Message__c=e.getMessage(), GlicW__Error_Trace__c=e.getStackTraceString()); }
   }

}
